# Generated by Django 5.0.3 on 2024-03-26 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number should start with +375 and consist of 13 digits. For exemple +375291231212 ', regex='^\\+375(24|25|29|33|44)\\d{7}$')]),
        ),
    ]
