services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db_cozygames
      - cache_cozygames
    volumes:
      - .:/CozyGames
    networks:
      - cozygames_net

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/CozyGames
    depends_on:
      - db_cozygames
      - cache_cozygames
    command: celery -A cozygames_core worker --loglevel=info
    networks:
      - cozygames_net

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/CozyGames
    depends_on:
      - db_cozygames
      - cache_cozygames
    command: celery -A cozygames_core beat --loglevel=info
    networks:
      - cozygames_net

  db_cozygames:
    image: postgres
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    networks:
      - cozygames_net

  cache_cozygames:
    image: redis
    networks:
      - cozygames_net

networks:
  cozygames_net:

volumes:
  pgdata:
