# Generated by Django 5.0.3 on 2024-04-16 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_tournament_tournamentparticipant_tournamentwinner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'approved')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('OP', 'open'), ('CL', 'closed')], default='OP', max_length=2),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
