# Generated by Django 5.0.3 on 2024-04-11 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_clientreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
