# Generated by Django 5.0.3 on 2024-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_clientreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreview',
            name='photo',
        ),
        migrations.AddField(
            model_name='clientreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client_reviews/'),
        ),
    ]
